### ISSUE TITLE
traceur.js.map missing?

### ISSUE THREAD

**Issue by chovy** [jmcriffey/bower-traceur#10]

**Comment by guybedford** [comment]
Also had the same in https://github.com/jspm/jspm-cli/issues/771.

I think we need to remove the sourcemap entirely from `traceur.js`?

**Comment by jmcriffey** [comment]
I'm not sure about who might need the source map. Also I'm unsure why we are talking about traceur.js.map, as that file is not referenced anywhere as far as I can tell. The minified file does reference traceur.min.map, which does exist in the repo and when installed via bower. Did you delete that file? Removing that last commented line of the minified file will stop it from trying to find the source map.

With that being said, I am up for removing the source map. I don't ever use it, but it was requested quite a long time ago and I can see how it might be useful.

**Comment by guybedford** [comment]
@jmcriffey the source map generation in this repo itself is great, but there is a source map in the unminified source at https://raw.githubusercontent.com/jmcriffey/bower-traceur/master/traceur.js, which probably needs to be stripped here as part of the process now, perhaps something changed in Traceur recently only to cause this.

**Comment by jmcriffey** [comment]
Gotcha. Thanks for clearing that up @guybedford. I'm not sure why they don't include the `traceur.js.map` file in npm, that seems like it might be useful. I went ahead and updated the build script here to strip out that comment and I republished 0.0.89.

**Comment by guybedford** [comment]
Thanks!
